package com.example.eslamashraf.hangman;

import android.content.Intent;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.View;
import android.widget.TextView;

public class PlayActivity extends AppCompatActivity {

    String[] movies_words ;
    String[] animals_words;
    String[] sports_words ;
    String[] vocabs_words ;
    String[] celeb_words ;
    String[] food_words;
    String[] countries_words;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_play);

        TextView movies = (TextView)findViewById(R.id.Movies);
        TextView animals = (TextView)findViewById(R.id.Animals);
        TextView sports = (TextView)findViewById(R.id.Sports);
        TextView vocabs = (TextView)findViewById(R.id.vocabularies);
        TextView celeb = (TextView)findViewById(R.id.celebrates);
        final TextView food = (TextView)findViewById(R.id.food);
        TextView countries = (TextView)findViewById(R.id.countries);
        movies.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                set_movies_words();
                Intent intent= new Intent(PlayActivity.this,GameActivity.class);
                intent.putExtra("category","Movies");
                intent.putExtra("words",movies_words);
                startActivity(intent);
            }
        });
        animals.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                set_animals_words();
                Intent intent= new Intent(PlayActivity.this,GameActivity.class);
                intent.putExtra("category","Animals");
                intent.putExtra("words",animals_words);

                startActivity(intent);
            }
        });
        sports.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                set_sports_words();
                Intent intent= new Intent(PlayActivity.this,GameActivity.class);
                intent.putExtra("category","Sports");
                intent.putExtra("words",sports_words);
                startActivity(intent);
            }
        });
        vocabs.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                set_vocabs_words();
                Intent intent= new Intent(PlayActivity.this,GameActivity.class);
                intent.putExtra("category","vocabularies");
                intent.putExtra("words",vocabs_words);
                startActivity(intent);
            }
        });
        celeb.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                set_celeb_words();
                Intent intent= new Intent(PlayActivity.this,GameActivity.class);
                intent.putExtra("category","Celebrates");
                intent.putExtra("words",celeb_words);
                startActivity(intent);
            }
        });
        food.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                set_food_words();
                Intent intent= new Intent(PlayActivity.this,GameActivity.class);
                intent.putExtra("category","Food");
                intent.putExtra("words",food_words);

                startActivity(intent);
            }
        });
        countries.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                set_countries_words();
                Intent intent= new Intent(PlayActivity.this,GameActivity.class);
                intent.putExtra("category","Countries");
                intent.putExtra("words",countries_words);

                startActivity(intent);
            }
        });

    }

    void set_movies_words() //done
    {
        movies_words =new String[120];
        movies_words[0]="After Earth";
        movies_words[1]=    "Avatar";
        movies_words[2]=   "Titanic";
        movies_words[3]=   "Star Wars";
        movies_words[4]=   "Jurassic World";
        movies_words[5]=    "Harry Potter";
        movies_words[6]=    "Frozen";
        movies_words[7]=    "Beauty and the Beast";
        movies_words[8]=    "Iron Man";
        movies_words[9]=    "Black Panther";
        movies_words[10]=    "Minions";
        movies_words[11]=  "Captain America";
        movies_words[12]="Dark of the Moon";
        movies_words[13]=       "The Lord of the Rings";
        movies_words[14]=        "Skyfall";
        movies_words[15]=         "Age of Extinction";
        movies_words[16]=         "Toy Story";
        movies_words[17]=         "Despicable Me";
        movies_words[18]=  "Jurassic Park";
        movies_words[19]=    "Finding Dory";
        movies_words[20]=     "The Phantom Menace";
        movies_words[21]=     "Alice in Wonderland";
        movies_words[22]=      "Zootopia";
        movies_words[23]=      "An Unexpected Journey";
        movies_words[24]=      "The Dark Knight";
        movies_words[25]=      "The Lion King";
        movies_words[26]=       "The Jungle Book";
        movies_words[27]=       "The Desolation of Smaug";
        movies_words[28]=       "Welcome to the Jungle";
        movies_words[29]=       "Finding Nemo";
        movies_words[30]=      "The Two Towers";
        movies_words[31]=     "Shrek";
        movies_words[32]=      "Spider Man";
        movies_words[33]=     "Spectre";
        movies_words[34]=     "The Secret Life of Pets";
        movies_words[35]=   "Dawn of Justice";
        movies_words[36]=    "The Fellowship of the Ring";
        movies_words[37]=      "Wolf Warrior";
        movies_words[38]=      "The Hunger Games";
        movies_words[39]=     "Inside Out";
        movies_words[40]=      "Thor";
        movies_words[41]=      "Revenge of the Sith";
        movies_words[42]=      "Revenge of the Fallen";
        movies_words[43]=      "Inception";
        movies_words[44]=     "Wonder Woman";
        movies_words[45]=       "Independence Day";
        movies_words[46]=      "Fast And Furious";
        movies_words[47]=      "Deadpool";
        movies_words[48]=      "Maleficent";
        movies_words[49]=       "The Da Vinci Code";
        movies_words[50]=        "Coco";
        movies_words[51]=   "X Men";
        movies_words[52]=    "Madagascar";
        movies_words[53]=    "Suicide Squad";
        movies_words[54]=    "Monsters University";
        movies_words[55]=     "The Matrix Reloaded";
        movies_words[56]=    "Up";
        movies_words[57]=     "Gravity";
        movies_words[58]=     "Dawn of the Planet of the Apes";
        movies_words[59]=     "The Twilight Saga";
        movies_words[60]=    "Transformers";
        movies_words[61]=    "The Wizard of Oz";
        movies_words[62]=    "Terminator";
        movies_words[63]=    "The Godfather";
        movies_words[64]=    "Raiders of the Lost Ark";
        movies_words[65]=     "Jaws";
        movies_words[66]=     "Fight Club";
        movies_words[67]=    "Pulp Fiction";
        movies_words[68]=    "Forrest Gump";
        movies_words[69]=    "Saving Private Ryan";
        movies_words[70]=    "The Matrix";
        movies_words[71]=    "Braveheart";
        movies_words[72]=     "GoodFellas";
        movies_words[73]=     "The Usual Suspects";
        movies_words[74]=      "Die Hard";
        movies_words[75]=      "Taxi Driver";
        movies_words[76]=      "Rocky";
        movies_words[77]=      "Full Metal Jacket";
        movies_words[78]=      "Psycho";
        movies_words[79]=      "The Green Mile";
        movies_words[80]=      "The Big Lebowski";
        movies_words[81]=       "The Departed";
        movies_words[82]=       "Space Odyssey";
        movies_words[83]=       "The Great Wall";
        movies_words[84]=       "King Kong";
        movies_words[85]=         "Life of Pi";
        movies_words[86]=         "Snowden";
        movies_words[87]=         "Tangled";
        movies_words[88]=        "The Revenant";
        movies_words[89]=       "The Martian";
        movies_words[90]=   "Warcraft";
        movies_words[91]=    "Hercules";
        movies_words[92]=    "Hard Target";
        movies_words[93]=   "Homefront";
        movies_words[94]=   "Pirates of the Caribbean";
        movies_words[95]=   "Boss Baby";
        movies_words[96]=    "Blood Diamond";
        movies_words[96]=       "Fantastic Four";
        movies_words[98]=         "Focus";
        movies_words[99]=        "The Forbidden Kingdom";
        movies_words[100]=        "Inter The Forest";
        movies_words[101]=        "Catwoman";
        movies_words[102]=        "Mechanic Resurrection";
        movies_words[103]=        "Batman";
        movies_words[104]=        "Safe";
        movies_words[105]=      "San Andreas";
        movies_words[106]=      "Maze Runner";
        movies_words[107]=      "Dragon Blade";
        movies_words[108]=      "Alien";
        movies_words[109]=      "The Prestige";
        movies_words[110]=      "Dead Poets Society";
        movies_words[111]=      "The Bourne Identity";
        movies_words[112]=       "Gran Torino";
        movies_words[113]=       "The Incredibles";
        movies_words[114]=      "Cast Away";
        movies_words[115]="The Avengers";
        movies_words[116]=     "Home Alone";
        movies_words[117]= "American Hustle";
        movies_words[118]= "Django Unchained";
        movies_words[119]= "Dumb and Dumber";

    }

    void set_food_words()  //done
    {
        food_words = new String[120];

        food_words[0]="Berry";
        food_words[1]="Drupe";
        food_words[2]="Avocado";
        food_words[3]="Noodles ";
        food_words[4]="Almond";
        food_words[5]="Black beans";
        food_words[6]="Bluefish";
        food_words[7]="Bread";
        food_words[8]="Cabbage";
        food_words[9]="Cake";
        food_words[10]="Carrots";
        food_words[11]="Cheese";
        food_words[12]="Chicken";
        food_words[13]="Chocolate";
        food_words[14]="Coffee";
        food_words[15]="Cookies";
        food_words[16]="Cereal";
        food_words[17]="Dumplings";
        food_words[18]="Eggrolls";
        food_words[19]="Fajita";
        food_words[20]="French toast";
        food_words[21]="French dip";
        food_words[22]="Garlic";
        food_words[23]="Ginger";
        food_words[24]="Grapes";
        food_words[25]="Gumbo";
        food_words[26]="Grits";
        food_words[27]="Hamburger";
        food_words[28]="Honey";
        food_words[29]="Hash browns";
        food_words[30]="Hot dogs";
        food_words[31]="Hummus";
        food_words[32]="Ice cream";
        food_words[33]="Irish stew";
        food_words[34]="Indian food";
        food_words[35]="Italian bread";
        food_words[36]="Jambalaya";
        food_words[37]="Kale";
        food_words[38]="Ketchup";
        food_words[39]="Kiwi";
        food_words[40]="Lobster";
        food_words[41]="Lamb";
        food_words[42]="Lasagna";
        food_words[43]="Meatballs";
        food_words[44]="Milkshake";
        food_words[45]="Pizza";
        food_words[46]="Pepperoni";
        food_words[47]="Pancakes";
        food_words[48]="Quesadilla";
        food_words[49]="Spinach";
        food_words[50]="Spaghetti";
        food_words[51]="Tater tots";
        food_words[52]="Venison";
        food_words[53]="Waffles";
        food_words[54]="Walnuts";
        food_words[55]="Yogurt";
        food_words[56]="Zucchini";
        food_words[57]="chutney";
        food_words[58]="Salmon";
        food_words[59]="Sandwich";
        food_words[60]="Sauerkraut";
        food_words[61]="Turkey";
        food_words[62]="Turmeric";
        food_words[63]="Sundae";
        food_words[64]="Sweet potato";
        food_words[65]="Syrup";
        food_words[66]="Pretzel";
        food_words[67]="Pumpkin";
        food_words[68]="Meatloaf";
        food_words[69]="Beef Stroganoff";
        food_words[70]="Tacos";
        food_words[71]="Cheeseburger soup";
        food_words[72]="Chili";
        food_words[73]="Fettuccine Alfredo";
        food_words[74]="Calzones";
        food_words[75]="Roast Chicken";
        food_words[76]="Enchiladas";
        food_words[77]="Bunbury cake";
        food_words[78]="Barmbrack";
        food_words[79]="Boston bun";
        food_words[80]="Mozzarella";
        food_words[81]="Muffin";
        food_words[82]="Mushroom";
        food_words[83]="Mustard";
        food_words[84]="Mutton";
        food_words[85]="Lasagna";
        food_words[86]="Legumes";
        food_words[87]="Lemonade";
        food_words[88]="Lettuce";
        food_words[89]="Loaf";
        food_words[90]="Lobster";
        food_words[91]="Grain";
        food_words[92]="Green bean";
        food_words[93]="Green tea";
        food_words[94]="Guava";
        food_words[95]="Raisin bread";
        food_words[96]="Buttered popcorn";
        food_words[97]="Masala dosa";
        food_words[98]="Potato chips";
        food_words[99]="Seafood paella";
        food_words[100]="Chicken rice";
        food_words[101]="Tacos";
        food_words[102]="Stinky tofu";
        food_words[103]="Marzipan";
        food_words[104]="Chicken parm";
        food_words[105]="Chili crab";
        food_words[106]="Goi cuon";
        food_words[107]="Butter garlic crab";
        food_words[108]="Croissant";
        food_words[109]="Shish kebab";
        food_words[110]="Pastel de nata";
        food_words[111]="Donuts";
        food_words[112]="Bell pepper";
        food_words[113]="Bitter melon";
        food_words[114]="Bitter gourd";
        food_words[115]="Pumpkin";
        food_words[116]="Pineapple";
        food_words[117]="Squash";
        food_words[118]="Vanilla";
        food_words[119]= "Winter melon";
    }

    void set_celeb_words() //done
    {

        celeb_words =new String[120];

        celeb_words[0]= "Johnny Depp";
        celeb_words[1]=         "Arnold Schwarzenegger";
        celeb_words[2]=         "Jim Carrey";
        celeb_words[3]=         "Emma Watson";
        celeb_words[4]=         "Daniel Radcliffe";
        celeb_words[5]=         "Leonardo DiCaprio";
        celeb_words[6]=         "Tom Cruise";
        celeb_words[7]=         "Brad Pitt";
        celeb_words[8]=         "Charles Chaplin";
        celeb_words[9]=         "Morgan Freeman";
        celeb_words[10]=         "Tom Hanks";
        celeb_words[11]=         "Hugh Jackman";
        celeb_words[12]=         "Matt Damon";
        celeb_words[13]=         "Sylvester Stallone";
        celeb_words[14]=         "Will Smith";
        celeb_words[15]=         "Clint Eastwood";
        celeb_words[16]=         "Cameron Diaz";
        celeb_words[17]=         "George Clooney";
        celeb_words[18]=         "Steven Spielberg";
        celeb_words[19]=         "Harrison Ford";
        celeb_words[20]=         "Robert De Niro";
        celeb_words[21]=         "Al Pacino";
        celeb_words[22]=         "Robert Downey Jr";
        celeb_words[23]=         "Russell Crowe";
        celeb_words[24]=         "Liam Neeson";
        celeb_words[25]=         "Kate Winslet";
        celeb_words[26]=         "Mark Wahlberg";
        celeb_words[27]=         "Natalie Portman";
        celeb_words[28]=         "Pierce Brosnan";
        celeb_words[29]=         "Sean Connery";
        celeb_words[30]=         "Orlando Bloom";
        celeb_words[31]=         "Dwayne Johnson";
        celeb_words[32]=         "Jackie Chan";
        celeb_words[33]=         "Angelina Jolie";
        celeb_words[34]=         "Adam Sandler";
        celeb_words[35]=         "Scarlett Johansson";
        celeb_words[36]=         "Heath Ledger";
        celeb_words[37]=         "Anne Hathaway";
        celeb_words[38]=         "Jessica Alba";
        celeb_words[39]=         "Edward Norton";
        celeb_words[40]=         "Keira Knightley";
        celeb_words[41]=         "Bradley Cooper";
        celeb_words[42]=         "Will Ferrell";
        celeb_words[43]=         "Julia Roberts";
        celeb_words[44]=         "Nicolas Cage";
        celeb_words[45]=         "Daniel Craig";
        celeb_words[46]=         "Keanu Reeves";
        celeb_words[47]=         "Ian McKellen";
        celeb_words[48]=         "Halle Berry";
        celeb_words[49]=         "Bruce Willis";
        celeb_words[50]=         "Ben Stiller";
        celeb_words[51]=         "Tommy Lee Jones";
        celeb_words[52]=         "Denzel Washington";
        celeb_words[53]=         "Steve Carell";
        celeb_words[54]=         "Shia LaBeouf";
        celeb_words[55]=         "Megan Fox";
        celeb_words[56]=         "James Franco";
        celeb_words[57]=         "Mel Gibson";
        celeb_words[58]=         "Vin Diesel";
        celeb_words[59]=         "Tim Allen";
        celeb_words[60]=         "Robin Williams";
        celeb_words[61]=         "Kevin Spacey";
        celeb_words[62]=         "Jason Biggs";
        celeb_words[63]=         "Seann William Scott";
        celeb_words[64]=         "Van Damme";
        celeb_words[65]=         "Zach Galifianakis";
        celeb_words[66]=         "Owen Wilson";
        celeb_words[67]=         "Christian Bale";
        celeb_words[68]=         "Peter Jackson";
        celeb_words[69]=         "Sandra Bullock";
        celeb_words[70]=         "Bruce Lee";
        celeb_words[71]=         "Drew Barrymore";
        celeb_words[72]=         "Macaulay Culkin";
        celeb_words[73]=         "Jack Nicholson";
        celeb_words[74]=         "Bill Murray";
        celeb_words[75]=         "Sigourney Weaver";
        celeb_words[76]=         "Jake Gyllenhaal";
        celeb_words[77]=         "Kamal Haasan";
        celeb_words[78]=         "Jason Statham";
        celeb_words[79]=         "Jet Li";
        celeb_words[80]=         "Kate Beckinsale";
        celeb_words[81]=         "Rowan Atkinson";
        celeb_words[82]=         "Marlon Brando";
        celeb_words[83]=         "John Travolta";
        celeb_words[84]=         "Channing Tatum";
        celeb_words[85]=         "Ben Affleck";
        celeb_words[86]=         "Shah Rukh Khan";
        celeb_words[87]=         "Jennifer Aniston";
        celeb_words[88]=         "Emma Stone";
        celeb_words[89]=         "Chris Hemsworth";
        celeb_words[90]=         "James McAvoy";
        celeb_words[91]=         "James Cameron";
        celeb_words[92]=         "Amitabh Bachchan";
        celeb_words[93]=         "Brendan Fraser";
        celeb_words[94]=         "Rachel McAdams";
        celeb_words[95]=         "Tom Hiddleston";
        celeb_words[96]=         "Aamir Khan";
        celeb_words[97]=         "Rajinikanth";
        celeb_words[98]=         "Ronaldinho";
        celeb_words[99]=         "Ronaldo";
        celeb_words[100]=         "Zinedine Zidane";
        celeb_words[101]=         "Neymar";
        celeb_words[102]=         "Luis Suarez";
        celeb_words[103]=         "Kaka";
        celeb_words[104]=         "Messi";
        celeb_words[105]=         "Xavi";
        celeb_words[106]=         "Iniesta";
        celeb_words[107]=         "Aguero";
        celeb_words[108]=         "Pele";
        celeb_words[109]=         "Maradona";
        celeb_words[110]=         "Beckham";
        celeb_words[111]=         "Kim Kardashian";
        celeb_words[112]=         "Albert Einstein";
        celeb_words[113]=         "Isaac Newton";
        celeb_words[114]=         "Charles Darwin";
        celeb_words[115]=         "Thomas Edison";
        celeb_words[116]=         "Stephen Hawking";
        celeb_words[117]=         "Adolf Hitler";
        celeb_words[118]=         "Alfred Nobel";
        celeb_words[119]=         "Richard Feynman";



    }


    void set_countries_words()
    {
        countries_words = new String[120];

        countries_words[0]="Egypt";
        countries_words[1]="Angola";
        countries_words[2]="Argentina";
        countries_words[3]="Armenia";
        countries_words[4]="Australia";
        countries_words[5]="Austria";
        countries_words[6]="Azerbaijan";
        countries_words[7]="Bahamas";
        countries_words[8]="Bahrain";
        countries_words[9]="Bangladesh";
        countries_words[10]="Barbados";
        countries_words[11]="Belarus";
        countries_words[12]="Belgium";
        countries_words[13]="Belize";
        countries_words[14]="Benin";
        countries_words[15]="Bhutan";
        countries_words[16]="Bolivia";
        countries_words[17]="Bosnia and Herzegovina";
        countries_words[18]="Botswana";
        countries_words[19]="Brazil";
        countries_words[20]="Brunei";
        countries_words[21]="Bulgaria";
        countries_words[22]="Burkina Faso";
        countries_words[23]="Burma";
        countries_words[24]="Burundi";
        countries_words[25]="Cambodia";
        countries_words[26]="Cameroon";
        countries_words[27]="Canada";
        countries_words[28]="Cape Verde";
        countries_words[29]="Central African Republic";
        countries_words[30]="Chad";
        countries_words[31]="Chile";
        countries_words[32]="China";
        countries_words[33]="Colombia";
        countries_words[34]="Comoros";
        countries_words[35]="Costa Rica";
        countries_words[36]="Croatia";
        countries_words[37]="Cuba";
        countries_words[38]="Cyprus";
        countries_words[39]="Czech Republic";
        countries_words[40]="Denmark";
        countries_words[41]="Djibouti";
        countries_words[42]="Dominica";
        countries_words[43]="Dominican Republic";
        countries_words[44]="East Timor";
        countries_words[45]="Ecuador";
        countries_words[46]="El Salvador";
        countries_words[47]="Equatorial Guinea";
        countries_words[48]="Eritrea";
        countries_words[49]="Estonia";
        countries_words[50]="Ethiopia";
        countries_words[51]="Finland";
        countries_words[52]="France";
        countries_words[53]="Gabon";
        countries_words[54]="Gambia";
        countries_words[55]="Georgia";
        countries_words[56]="Germany";
        countries_words[57]="Ghana";
        countries_words[58]="Greece";
        countries_words[59]="Grenada";
        countries_words[60]="Guatemala";
        countries_words[61]="Guinea";
        countries_words[62]="Guinea Bissau";
        countries_words[63]="Guyana";
        countries_words[64]="Haiti";
        countries_words[65]="Honduras";
        countries_words[66]="Hungary";
        countries_words[67]="Iceland";
        countries_words[68]="India";
        countries_words[69]="Indonesia";
        countries_words[70]="Iran";
        countries_words[71]="Iraq";
        countries_words[72]="Ireland";
        countries_words[73]="Italy";
        countries_words[74]="Jamaica";
        countries_words[75]="Japan";
        countries_words[76]="Jordan";
        countries_words[77]="Kazakhstan";
        countries_words[78]="Kenya";
        countries_words[79]="Turkey";
        countries_words[80]="Korea North";
        countries_words[81]="Korea South";
        countries_words[82]="Kuwait";
        countries_words[83]="Kyrgyzstan";
        countries_words[84]="Laos";
        countries_words[85]="Latvia";
        countries_words[86]="Lebanon";
        countries_words[87]="Lesotho";
        countries_words[88]="Liberia";
        countries_words[89]="Libya";
        countries_words[90]="Liechtenstein";
        countries_words[91]="Lithuania";
        countries_words[92]="Luxembourg";
        countries_words[93]="Macedonia";
        countries_words[94]="Madagascar";
        countries_words[95]="Malawi";
        countries_words[96]="Malaysia";
        countries_words[97]="Maldives";
        countries_words[98]="Mali";
        countries_words[99]="Malta";
        countries_words[100]="United States";
        countries_words[101]="Mauritania";
        countries_words[102]="Mauritius";
        countries_words[103]="Mexico";
        countries_words[104]="Micronesia";
        countries_words[105]="Moldova";
        countries_words[106]="Monaco";
        countries_words[107]="United Kingdom";
        countries_words[108]="Montenegro";
        countries_words[109]="Morocco";
        countries_words[110]="Mozambique";
        countries_words[111]="Myanmar";
        countries_words[112]="Netherlands";
        countries_words[113]="Palestinian";
        countries_words[114]="Portugal";
        countries_words[115]="Russia";
        countries_words[116]="Saudi Arabia";
        countries_words[117]="Senegal";
        countries_words[118]="Syria";
        countries_words[119]="Spain";
    }
    void set_animals_words()
    {

        animals_words = new String[120];
        animals_words[0]="Baboon";
        animals_words[1]="Badger";
        animals_words[2]="Balinese";
        animals_words[3]="Bandicoot";
        animals_words[4]="Barb";
        animals_words[5]="Barn Owl";
        animals_words[6]="Barnacle";
        animals_words[7]="Barracuda";
        animals_words[8]="Caiman";
        animals_words[9]="Cairn Terrier";
        animals_words[10]="Camel";
        animals_words[11]="Capybara";
        animals_words[12]="Caracal";
        animals_words[13]="Cassowary";
        animals_words[14]="Cat";
        animals_words[15]="Caterpillar";
        animals_words[16]="Catfish";
        animals_words[17]="Centipede";
        animals_words[18]="Cesky Fousek";
        animals_words[19]="Chameleon";
        animals_words[20]="Chamois";
        animals_words[21]="Cheetah";
        animals_words[22]="Chicken";
        animals_words[23]="Chihuahua";
        animals_words[24]="Chimpanzee";
        animals_words[25]="Chinchilla";
        animals_words[26]="Chinook";
        animals_words[27]="Chipmunk";
        animals_words[28]="Cichlid";
        animals_words[29]="Clouded Leopard";
        animals_words[30]="Clown Fish";
        animals_words[31]="Coati";
        animals_words[32]="Cockroach";
        animals_words[33]="Collared Peccary";
        animals_words[34]="Collie";
        animals_words[35]="Common Buzzard";
        animals_words[36]="Coral";
        animals_words[37]="Cougar";
        animals_words[38]="Cow";
        animals_words[39]="Coyote";
        animals_words[40]="Crab";
        animals_words[41]="Crane";
        animals_words[42]="Crested Penguin";
        animals_words[43]="Crocodile";
        animals_words[44]="Eagle";
        animals_words[45]="Earwig";
        animals_words[46]="Eastern Gorilla";
        animals_words[47]="Echidna";
        animals_words[48]="Edible Frog";
        animals_words[49]="Mau";
        animals_words[50]="Electric Eel";
        animals_words[51]="Elephant";
        animals_words[52]="Emu";
        animals_words[53]="Falcon";
        animals_words[54]="Fox";
        animals_words[55]="Ferret";
        animals_words[56]="Fin Whale";
        animals_words[57]="Finnish Spitz";
        animals_words[58]="Fishing Cat";
        animals_words[59]="Flamingo";
        animals_words[60]="Flounder";
        animals_words[61]="Fossa";
        animals_words[62]="Frigatebird";
        animals_words[63]="Galapagos Penguin";
        animals_words[64]="Galapagos Tortoise";
        animals_words[65]="Gar";
        animals_words[66]="Gharial";
        animals_words[67]="Gibbon";
        animals_words[68]="Gila Monster";
        animals_words[69]="Giraffe";
        animals_words[70]="Glass Lizard";
        animals_words[71]="Glow Worm";
        animals_words[72]="Goat";
        animals_words[73]="Goose";
        animals_words[74]="Gopher";
        animals_words[75]="Gorilla";
        animals_words[76]="Frog";
        animals_words[77]="Ostrich";
        animals_words[78]="Otter";
        animals_words[79]="Saola";
        animals_words[80]="Scorpion";
        animals_words[81]="Seahorse";
        animals_words[82]="Seal";
        animals_words[83]="Serval";
        animals_words[84]="Sheep";
        animals_words[85]="Shih Tzu";
        animals_words[86]="Shrimp";
        animals_words[87]="Siamese";
        animals_words[88]="Siberian";
        animals_words[89]="Skunk";
        animals_words[90]="Sloth";
        animals_words[91]="Slow Worm";
        animals_words[92]="Snail";
        animals_words[93]="Snake";
        animals_words[94]="Sponge";
        animals_words[95]="Squid";
        animals_words[96]="Squirrel";
        animals_words[97]="Stag Beetle";
        animals_words[98]="Starfish";
        animals_words[99]="Stoat";
        animals_words[100]="Sun Bear";
        animals_words[101]="Zebra";
        animals_words[102]="Tang";
        animals_words[103]="Tapir";
        animals_words[104]="Tarsier";
        animals_words[105]="Tasmanian Devil";
        animals_words[106]="Tawny Owl";
        animals_words[107]="Termite";
        animals_words[108]="Tetra";
        animals_words[109]="Thorny Devil";
        animals_words[110]="Tibetan Mastiff";
        animals_words[111]="Tiffany";
        animals_words[112]="Tiger";
        animals_words[113]="Tiger Salamander";
        animals_words[114]="Tiger Shark";
        animals_words[115]="Tortoise";
        animals_words[116]="Toucan";
        animals_words[117]="Tree Frog";
        animals_words[118]="Liger";
        animals_words[119]="Lion";

    }
    void set_vocabs_words() //done
    {
        vocabs_words = new String[120];

        vocabs_words[0]="Aisle";
        vocabs_words[1]="Door";
        vocabs_words[2]="Wild";
        vocabs_words[3]="Car";
        vocabs_words[4]="Woman";
        vocabs_words[5]="Camel";
        vocabs_words[6]="Arrival";
        vocabs_words[7]="Baggage";
        vocabs_words[8]="Board";
        vocabs_words[9]="Carry-on";
        vocabs_words[10]="Coach";
        vocabs_words[11]="Declare";
        vocabs_words[12]="Luggage";
        vocabs_words[13]="Gate";
        vocabs_words[14]="Customer";
        vocabs_words[15]="Connection";
        vocabs_words[16]="Cockpit";
        vocabs_words[17]="Oxygen";
        vocabs_words[18]="Passport";
        vocabs_words[19]=" Runway";
        vocabs_words[20]="Boarding pass";
        vocabs_words[21]="Security";
        vocabs_words[22]="Turbulence";
        vocabs_words[23]="Atmosphere";
        vocabs_words[24]="Biodiversity";
        vocabs_words[25]= "Carbon dioxide";
        vocabs_words[26]="Climate";
        vocabs_words[27]="Coal";
        vocabs_words[28]="Compost";
        vocabs_words[29]="Conservation";
        vocabs_words[30]= "Environment";
        vocabs_words[31]="Global warming";
        vocabs_words[32]="Petroleum";
        vocabs_words[33]="Recycle";
        vocabs_words[34]="Waste";
        vocabs_words[35]="Grandmother";
        vocabs_words[36]="Grandfather";
        vocabs_words[37]="Grandson";
        vocabs_words[38]="Accountant";
        vocabs_words[39]="Actor";
        vocabs_words[40]="Bookkeeper";
        vocabs_words[41]="Cashier";
        vocabs_words[42]="Chef";
        vocabs_words[43]="Butcher";
        vocabs_words[44]="Developer";
        vocabs_words[45]="Example";
        vocabs_words[46]="Doctor";
        vocabs_words[47]="Economist";
        vocabs_words[48]="Engineer";
        vocabs_words[49]="Musician";
        vocabs_words[50]="Nutritionist";
        vocabs_words[51]=" Nurse";
        vocabs_words[52]="Acceptance";
        vocabs_words[53]="Admiration";
        vocabs_words[54]="Affection";
        vocabs_words[55]="Aggravation";
        vocabs_words[56]="Anger";
        vocabs_words[57]="Anguish";
        vocabs_words[58]="Attraction";
        vocabs_words[59]="Contentment";
        vocabs_words[60]="Courage";
        vocabs_words[61]="Paragraph";
        vocabs_words[62]="Blocks";
        vocabs_words[63]="Papers";
        vocabs_words[64]="Student";
        vocabs_words[65]="Teacher";
        vocabs_words[66]="Panicle";
        vocabs_words[67]="Terms";
        vocabs_words[68]="Least";
        vocabs_words[69]="Sentences";
        vocabs_words[70]="Important";
        vocabs_words[71]="Organize";
        vocabs_words[72]="Curiosity";
        vocabs_words[73]="Defiance";
        vocabs_words[74]="Dependence";
        vocabs_words[75]="Disappointment";
        vocabs_words[76]="Adventurous";
        vocabs_words[77]="Affectionate";
        vocabs_words[78]="Ambitious";
        vocabs_words[79]="Application";
        vocabs_words[80]="Benefit";
        vocabs_words[81]="Bonus";
        vocabs_words[82]="Career";
        vocabs_words[83]="Employee";
        vocabs_words[84]="Interview" ;
        vocabs_words[85]="Postgraduate";
        vocabs_words[86]="Prerequisite";
        vocabs_words[87]="Professor";
        vocabs_words[88]="Budget";
        vocabs_words[89]="Degree";
        vocabs_words[90]="Competition";
        vocabs_words[91]="Depression";
        vocabs_words[92]=" Investment";
        vocabs_words[93]="International";
        vocabs_words[94]="Recession";
        vocabs_words[95]="Savings";
        vocabs_words[96]="Spending";
        vocabs_words[97]="Shopping";
        vocabs_words[98]="Investigators";
        vocabs_words[99]="Committee ";
        vocabs_words[100]="Feature";
        vocabs_words[101]="People";
        vocabs_words[102]="Extinguisher";
        vocabs_words[103]="Question";
        vocabs_words[104]="Children's";
        vocabs_words[105]="Individual";
        vocabs_words[106]="Infiltrated";
        vocabs_words[107]="Luxury goods";
        vocabs_words[108]="Successful";
        vocabs_words[109]="Longer";
        vocabs_words[110]="Address";
        vocabs_words[111]="Always";
        vocabs_words[112]="Amount";
        vocabs_words[113]="Animal";
        vocabs_words[114]="Beautiful";
        vocabs_words[115]="Blood";
        vocabs_words[116]="Business";
        vocabs_words[117]="Certainly";
        vocabs_words[118]="Cover";
        vocabs_words[119]="Difference";

    }

    void set_sports_words() //done
    {
        sports_words=new String[120];
        sports_words[0]=  "Stadium";
        sports_words[1]=                 "Captain";
        sports_words[2]=                 "Team";
        sports_words[3]=                 "Skill";
        sports_words[4]=                 "Athlete";
        sports_words[5]=                 "Tournament";
        sports_words[6]=                 "Coach";
        sports_words[7]=                 "Medal";
        sports_words[8]=                 "Competitor";
        sports_words[9]=                 "Professional";
        sports_words[10]=                 "Contest";
        sports_words[11]=                 "Referee";
        sports_words[12]=                 "Defeat";
        sports_words[13]=                 "Spectator";
        sports_words[14]=                 "League";
        sports_words[15]=                 "Victory";
        sports_words[16]=                 "Season";
        sports_words[17]=                 "Amateur";
        sports_words[18]=                 "Corner";
        sports_words[19]=                 "Pass";
        sports_words[20]=                 "Handball";
        sports_words[21]=                 "Clearance";
        sports_words[22]=                 "Header";
        sports_words[23]=                 "Cross";
        sports_words[24]=                 "Kick Off";
        sports_words[25]=                 "Goal Kick";
        sports_words[26]=                 "Free Kick";
        sports_words[27]=                 "Shoot";
        sports_words[28]=                 "Penalty";
        sports_words[29]=                 "Win";
        sports_words[30]=                 "Draw";
        sports_words[31]=                 "Knock Out";
        sports_words[32]=                 "Equalizer";
        sports_words[33]=                 "Leader";
        sports_words[34]=                 "Extra Time";
        sports_words[35]=                 "Offside";
        sports_words[36]=                 "Full Time";
        sports_words[37]=                 "Foul";
        sports_words[38]=                 "Attacker";
        sports_words[39]=                 "Midfielder";
        sports_words[40]=                 "Defender";
        sports_words[41]=                 "Goalkeeper";
        sports_words[42]=                 "Linesman";
        sports_words[43]=                 "Referee";
        sports_words[44]=                 "Match";
        sports_words[45]=                 "Archery";
        sports_words[46]=                 "Athletics";
        sports_words[47]=                 "Billiards";
        sports_words[48]=                 "Bobsleigh";
        sports_words[49]=                 "Bowling";
        sports_words[50]=                 "Boxing";
        sports_words[51]=                 "Canoe";
        sports_words[52]=                 "Canoe Slalom";
        sports_words[53]=                 "Chess";
        sports_words[54]=                 "Climbing";
        sports_words[55]=                 "Cycling";
        sports_words[56]=                 "Darts";
        sports_words[57]=                 "Discus";
        sports_words[58]=                 "Fishing";
        sports_words[59]=                 "Formula";
        sports_words[60]=                 "Slalom";
        sports_words[61]=                 "Gymnastics";
        sports_words[62]=                 "Hammer Throwing";
        sports_words[63]=                 "Hang Gliding";
        sports_words[64]=                 "Diving";
        sports_words[65]=                 "Hiking";
        sports_words[66]=                 "Racing";
        sports_words[67]=                 "Hunting";
        sports_words[68]=                 "Hurdle Race";
        sports_words[69]=                 "Ice Hockey";
        sports_words[70]=                 "Javelin";
        sports_words[71]=                 "Jogging";
        sports_words[72]=                 "Long Jump";
        sports_words[73]=                 "Luge";
        sports_words[74]=                 "Pentathlon";
        sports_words[75]=                 "Motorsports";
        sports_words[76]=                 "Mountaineering";
        sports_words[77]=                 "Netball";
        sports_words[78]=                 "Nordic Combined";
        sports_words[79]=                 "Paintball";
        sports_words[80]=                 "Parachuting";
        sports_words[81]=                 "Rope";
        sports_words[82]=                 "Skipping";
        sports_words[83]=                 "Rowing";
        sports_words[84]=                 "Running";
        sports_words[85]=                 "Sailing";
        sports_words[86]=                 "Shooting";
        sports_words[87]=                 "Skating";
        sports_words[88]=                 "Jumping";
        sports_words[89]=                 "Skiing";
        sports_words[90]=                 "Snowboarding";
        sports_words[91]=                 "Soccer";
        sports_words[92]=                 "Football";
        sports_words[93]=                 "Skating";
        sports_words[94]=                 "Sprint";
        sports_words[95]=                 "Surfing";
        sports_words[96]=                 "Swimming";
        sports_words[97]=                 "Table Tennis";
        sports_words[98]=                 "Tennis";
        sports_words[99]=                 "Tug Of War";
        sports_words[100]=                 "Walking";
        sports_words[101]=                 "Water Polo";
        sports_words[102]=                 "Weight";
        sports_words[103]=                 "Lifting";
        sports_words[104]=                 "Windsurfing";
        sports_words[105]=                 "Wrestling";
        sports_words[106]=                 "Hurling";
        sports_words[107]=                 "Track And Field";
        sports_words[108]=                 "Baseball";
        sports_words[109]=                 "Rugby";
        sports_words[110]=                 "Volleyball";
        sports_words[111]=                 "Cricket";
        sports_words[112]=                 "Basketball";
        sports_words[113]=                 "Red Card";
        sports_words[114]=                 "Yellow Card";
        sports_words[115]=                 "Striker";
        sports_words[116]=                 "Jump Shot";
        sports_words[117]=                 "Block";
        sports_words[118]=                 "Clinch";
        sports_words[119]=                 "Break";

    }
}
